### ISSUE TITLE
Allow configurable user timeouts

### ISSUE THREAD

**Issue by bkgoodman** [makeitlabs/ratt#5]
Allow idle/timeouts to be configurable, and maybe allow this to differ w/ user privs.

Specifically, I'd like to have MUCH longer timeouts for ARMs doing maintenance.

**Comment by tangentaudio** [comment]
I have a good idea how to approach this based on the "level" field supplied in the v1 ACL.  I will add an "admin timeout" config to the individual RATT, and anyone who is configured above level 0 for that resource will have that timeout.

One minor concern is that since admin accounts are semi-privileged, the normal security model is to make things like timeouts MORE restrictive, not less, to prevent things like coat-tailing (if an admin forgot to log out and wandered away, the tool might have a 1 hour timeout, and a different person could use it without badging in).  Would it be objectionable to have to perform some kind of sequence to put it into that extended maintenance/teaching mode (like, badge in holding down a button)?

**Comment by bkgoodman** [comment]
That wouldn't be bad - to have to do something specific to put into a "longer term" mode.

Just as long as Bug #6 was dealt with - this is probably the more annoying one.

**Comment by tangentaudio** [comment]
Fixed, there's now a configurable option called  `[Personality] AdminTimeoutSeconds` in the config file.  Anyone with a `level` > 0 in the ACL will have the option to engage a longer timeout by long-pressing the blue button when logged into RATT.
